version: '3.1'
services:
  php:
    container_name: laravel-ecosystem
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: laravel-ecosystem:latest
    networks:
        - laravel-ecosystem-net
    volumes:
      - ../:/usr/share/app
    environment:
      - ENVIRONMENT=development
  nginx:
    container_name: laravel-ecosystem-nginx
    image: nginx
    env_file:
        - ../.env
    restart: always
    networks:
        - laravel-ecosystem-net
    links:
        - mariadb
        - mongodb
        - php
    depends_on:
        - mariadb
        - mongodb
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/servers:/etc/nginx/servers
      - ./keys/nginx:/keys
      - ../:/usr/share/app
  mariadb:
    container_name: laravel-ecosystem-mariadb
    image: mariadb:10.5
    env_file:
        - ./.env
    restart: always
    networks:
        - laravel-ecosystem-net
    ports:
        - "3376:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./etc/mariadb/my.cnf.d:/etc/mysql/conf.d
  mongodb:
    container_name: laravel-ecosystem-mongo
    image: bitnami/mongodb:4.2
    env_file:
        - ./.env
    restart: always
    networks:
        - laravel-ecosystem-net
    ports:
        - "27018:27017"
    volumes:
        - ./data/mongodb:/data
        - mongo-data-dev:/bitnami/mongodb
networks:
    laravel-ecosystem-net: {}
volumes:
    mongo-data-dev:
